{% set name = "mod_wsgi" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81fa192494410f2a4760818a7bfd7fa65826158d08af6726ec6a1b3d0ee18b3a

build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mod_wsgi-express = mod_wsgi.server:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mod_wsgi

about:
  home: https://modwsgi.readthedocs.io/en/developi/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Apache module that implements a WSGI compliant interface for hosting Python based web applications

  description: |
    mod_wsgi is a module for the Apache HTTP server that allows the web server to execute Python programs. WSGI (Web Server Gateway Interface) is a general interface between the Web server and Python applications.
  doc_url: https://modwsgi.readthedocs.io/en/develop/
  dev_url: https://github.com/GrahamDumpleton/mod_wsgi

extra:
  recipe-maintainers:
    - ReimarBauer
