schema_version: 1

context:
  name: mod_wsgi
  version: "6.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9ebb645c899ea6461edf27872c11a6a12c6e819edbcc3652e0b6195d990aa31c

build:
  number: 0
  skip: win
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - mod_wsgi-express = mod_wsgi.express.cli:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - libpython
    - pip
    - setuptools
  run:
    - python

tests:
  - script:
      content:
        - mod_wsgi-express module-config
  - python:
      imports:
        - mod_wsgi
      pip_check: false

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Apache module that implements a WSGI compliant interface for hosting Python based web applications
  description: |
    mod_wsgi is a module for the Apache HTTP server that allows the web server to execute Python programs. WSGI (Web Server Gateway Interface) is a general interface between the Web server and Python applications.
  homepage: https://modwsgi.readthedocs.io/en/developi/
  repository: https://github.com/GrahamDumpleton/mod_wsgi
  documentation: https://modwsgi.readthedocs.io/en/develop/

extra:
  recipe-maintainers:
    - akrherz
    - ReimarBauer
